title: Edwin Noh's Blog
description: This is a space to log edwin's
theme: just-the-docs

url: https://edwin-noh.github.io

aux_links:
  Template Repository: https://github.com/edwin-noh/edwin-noh.github.io
